/* MOON LIGHT SOURCE */
(function(){const _0x1='https://moon-api.reallyfrostpvp-b61.workers.dev';const _0x2='token';function _0x3(){return localStorage.getItem(_0x2)}function _0x4(t){localStorage.setItem(_0x2,t)}function _0x5(){localStorage.removeItem(_0x2)}
document.querySelectorAll('nav a[data-page], .btn[data-page]').forEach(function(e){e.addEventListener('click',function(ev){ev.preventDefault();const p=ev.target.dataset.page;if(!p)return;document.querySelectorAll('.section').forEach(function(s){s.classList.remove('active')});document.getElementById(p).classList.add('active')})});
async function _0x6(){const t=_0x3();const n=document.getElementById('navAuth');if(t){n.innerHTML='<a href="#" data-page="profile">Profile</a> <a href="#" id="logoutLink">Logout</a>';document.getElementById('logoutLink').addEventListener('click',function(){_0x5();location.reload()});if(document.getElementById('profile').classList.contains('active')){_0x7()}}else{n.innerHTML='<a href="#" data-page="login">Login</a> <a href="#" data-page="register">Register</a>'}}
document.getElementById('registerBtn').addEventListener('click',async function(){const u=document.getElementById('regUsername').value.trim();const e=document.getElementById('regEmail').value.trim();const p=document.getElementById('regPassword').value;const er=document.getElementById('regError');if(!u||!e||!p){er.textContent='All fields required';return}
er.textContent='Registering...';try{const r=await fetch(_0x1+'/api/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:u,email:e,password:p})});const t=await r.text();if(!r.ok){er.textContent=t||'Registration failed';return}
alert('Registered! Please login.');document.querySelectorAll('.section').forEach(function(s){s.classList.remove('active')});document.getElementById('login').classList.add('active');er.textContent=''}catch(e){er.textContent='Network error – check console (F12)';console.error(e)}});
document.getElementById('loginBtn').addEventListener('click',async function(){const e=document.getElementById('loginEmail').value.trim();const p=document.getElementById('loginPassword').value;const er=document.getElementById('loginError');if(!e||!p){er.textContent='All fields required';return}
er.textContent='Logging in...';try{const r=await fetch(_0x1+'/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:e,password:p})});const t=await r.text();if(!r.ok){er.textContent=t||'Invalid credentials';return}
const d=JSON.parse(t);_0x4(d.token);location.reload()}catch(e){er.textContent='Network error – check console';console.error(e)}});
async function _0x7(){const t=_0x3();if(!t)return;try{const r=await fetch(_0x1+'/api/me',{headers:{'Authorization':`Bearer ${t}`}});if(!r.ok)throw new Error('Unauthorized');const u=await r.json();document.getElementById('profileUsername').textContent=u.username;document.getElementById('profileKey').textContent='Key: '+u.key;document.getElementById('nicknameInput').value=u.nickname||'';document.getElementById('avatarUrlInput').value=u.avatar_url||'';const statusEl=document.getElementById('profileStatus');if(statusEl){statusEl.textContent=u.active?'Active':'Banned';statusEl.style.color=u.active?'#4ade80':'#f87171'}}catch(e){_0x5();location.reload()}}
document.getElementById('saveProfileBtn').addEventListener('click',async function(){const t=_0x3();if(!t)return;const nick=document.getElementById('nicknameInput').value.trim();const ava=document.getElementById('avatarUrlInput').value.trim();await fetch(_0x1+'/api/me',{method:'PATCH',headers:{'Authorization':`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({nickname:nick,avatar_url:ava})});alert('Profile updated!');_0x7()});
document.getElementById('changeEmailBtn').addEventListener('click',async function(){const t=_0x3();const ne=document.getElementById('newEmail').value.trim();if(!ne)return;const r=await fetch(_0x1+'/api/me/email',{method:'PATCH',headers:{'Authorization':`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({email:ne})});if(r.ok)alert('Email updated!');else alert('Error: '+(await r.text()))});
document.getElementById('changePasswordBtn').addEventListener('click',async function(){const t=_0x3();const cp=document.getElementById('currentPassword').value;const np=document.getElementById('newPassword').value;if(!cp||!np)return;const r=await fetch(_0x1+'/api/me/password',{method:'PATCH',headers:{'Authorization':`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({currentPassword:cp,newPassword:np})});if(r.ok)alert('Password changed!');else alert('Error: '+(await r.text()))});
fetch('status.json').then(function(r){return r.json()}).then(function(d){const dot=document.getElementById('statusDot');const txt=document.getElementById('statusText');dot.style.background=d.color;dot.style.boxShadow='0 0 20px '+d.color;txt.textContent=d.text;document.getElementById('statusDetails').textContent='Last updated: '+new Date().toLocaleString()}).catch(function(){document.getElementById('statusDot').style.background='gray';document.getElementById('statusText').textContent='Status unavailable'});
_0x6()})();
